### ISSUE TITLE
Challenge verification failed!

### ISSUE THREAD

**Issue by volkanunsal** [lgromanowski/letsencrypt-plugin#33]
#### 1. Expected behavior
I expect the challenge verification to succeed.

#### 2. Actual behavior 
Instead I get this error message:

```
ERROR -- : Challenge verification failed! Error: urn:acme:error:unauthorized: Invalid response from http://myapp.com/.well-known/acme-challenge/my_id 404
```

#### 3. Steps to reproduce issue
I've followed the Getting Started instructions. This happens, I think, because Rails doesn't like dots at the base of the path.

#### 4. Your configuration (ruby, rails version, your Gemifile and Gemfile.lock files etc.)

```ruby
source 'http://rubygems.org'
ruby '2.2.2'

gem 'rails', '4.2.6'
```

**Comment by lgromanowski** [comment]
Hi,
could you please post your `config/letsencrypt_config.yml` file?

**Comment by volkanunsal** [comment]
```yml
default: &default
  endpoint: 'https://acme-v01.api.letsencrypt.org/'
  email: 'my_email@gmail.com'
  domain: 'example.com'

  # in Rails.root, path to private key
  private_key: 'config/key/keyfile.pem'

  # in Rails.root, path where certificates
  # will be stored (on Heroku this variable is ignored)
  output_cert_dir: 'config/certificates'

  # in Rails.root, path where challenge token
  # will be stored in case when DB will not be used
  # challenge_dir_name: 'config/challenge'

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default

```
